"use client";
import { createContext,useContext,useEffect,useMemo,useState } from "react";
import { Activity,Check,CheckCircle2,ChevronDown,Clock3,Download,Edit3,LockKeyhole,LogOut,RefreshCw,Save,Search,Sparkles,Target,Users,X } from "lucide-react";
import { Bar,BarChart,CartesianGrid,Cell as ChartCell,LabelList,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { workbookData } from "./workbook-data";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Cell=string|number|boolean|null; type Sheet={range:string;values:Cell[][];formulas:(string|null)[][]}; type Book=Record<string,Sheet>;
const AdminContext=createContext(false);
const ADMIN_HASH="8000223af6ce20f37c83348ab2910ec317898f3bb649f6015864d28432a31c4b";
type Multi={pillars:string[];pics:string[];statuses:string[]};
type Penalty={opening:number;attendance:number;action:number;master:number;total:number};
const hidden=new Set(["01. OE Team","01. Steering Committee","02. RASCI"]);
const names=[...Object.keys(workbookData).filter(n=>!hidden.has(n)),"Budget management"];
const short:Record<string,string>={"03. Attendance":"Attendance","04. Agenda":"Agenda","05. Master Planning":"Master Planning","06. Action Plan":"Action Plan","7. KPI Measure":"KPI Measure","KPI data tracking":"KPI Tracking","OE meeting rules":"Meeting Rules","Engagement plan":"Engagement","Budget management":"Budget Management"};
const tx=(v:Cell)=>v==null?"":String(v);
const numberFormat=new Intl.NumberFormat("en-US",{minimumFractionDigits:1,maximumFractionDigits:1});
const formatNumber=(v:Cell)=>v==null||v===""?"":Number.isFinite(Number(v))?numberFormat.format(Number(v)):tx(v);
function excelDate(v:Cell){if(typeof v!=="number"||v<40000||v>60000)return tx(v);return new Date(Date.UTC(1899,11,30)+v*86400000).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})}
function tone(v:Cell){const s=tx(v).toLowerCase();if(s==="done"||s==="1")return"done";if(s.includes("late")||s==="2")return"late";if(s.includes("going")||s.includes("progress")||s==="3")return"going";if(s.includes("cancel")||s==="4")return"muted";return""}
const hasValue=(r:Cell[])=>r.some(v=>v!==null&&v!=="");
const key=(v:Cell)=>tx(v).trim().toLowerCase();
const openingBalances:Record<string,number>={"duc mai":0,"duy pham":0,"dung tran":70000,"vu tran":0,"nghia bui":10000,"binh dang":50000,"thu duong":80000,"hoang nguyen":50000};
const budgetSeed:Cell[][]=[["Duc Mai",600000,600000,null],["Duy Pham",300000,300000,null],["Dung Tran",600000,600000,null],["Vu Tran",300000,300000,null],["Nghia Bui",300000,300000,null],["Binh Dang",300000,300000,null],["Thu Duong",300000,300000,null],["Hoang Nguyen",600000,600000,null]];
function ensureBudget(next:Book){if(!next["Budget management"])next["Budget management"]={range:"A1:G12",values:JSON.parse(JSON.stringify(budgetSeed)),formulas:[]};while(next["Budget management"].values.length<13)next["Budget management"].values.push([null,null,null,null]);next["06. Action Plan"]?.values.forEach(r=>{if(tx(r[6]).toLowerCase().replace(/\s/g,"")==="ongoing")r[6]="Ongoing"});return next}
function freshBook(){const next=ensureBudget(JSON.parse(JSON.stringify(workbookData)) as Book);next["03. Attendance"].values.slice(3,13).forEach(r=>r[29]=0);return next}
function isoWeek(date=new Date()){const d=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate())),day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const start=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d.getTime()-start.getTime())/86400000)+1)/7)}
function calculatePenalties(book:Book){
 const result:Record<string,Penalty>={}; const ensure=(name:Cell)=>result[key(name)]??(result[key(name)]={opening:openingBalances[key(name)]||0,attendance:0,action:0,master:0,total:0});
 book["03. Attendance"].values.slice(3,13).forEach(r=>{if(!r[1])return;const p=ensure(r[1]);r.slice(17,25).forEach(v=>{if(tx(v)==="2")p.attendance+=20000;if(tx(v)==="3")p.attendance+=50000})});
 const weeks=book["05. Master Planning"].values[3];book["05. Master Planning"].values.slice(4).forEach(r=>{if(!r[2])return;const p=ensure(r[2]);p.master+=r.filter((v,c)=>c>=4&&Number(weeks[c])>=36&&(tx(v).toLowerCase()==="3"||tx(v).toLowerCase()==="late")).length*10000});
 book["06. Action Plan"].values.slice(2).forEach(r=>{if(!r[4])return;const due=tx(r[5]),serial=typeof r[5]==="number"?r[5]:0,fromSep=serial>=46266||/sep/i.test(due);if(!fromSep)return;const p=ensure(r[4]),recorded=Math.max(0,Number(r[8])||0),late=tx(r[6]).toLowerCase()==="late";p.action+=(recorded||(late?1:0))*10000});
 Object.values(result).forEach(p=>p.total=p.attendance+p.action+p.master);return result;
}

export default function Home(){
 const [book,setBook]=useState<Book>(()=>freshBook()),[active,setActive]=useState("03. Attendance"),[query,setQuery]=useState("");
 const [masterPillar,setMasterPillar]=useState("All"),[masterPic,setMasterPic]=useState("All"),[multi,setMulti]=useState<Multi>({pillars:[],pics:[],statuses:[]}),[saved,setSaved]=useState(false),[admin,setAdmin]=useState(false),[loginOpen,setLoginOpen]=useState(false),[password,setPassword]=useState(""),[loginError,setLoginError]=useState(false);
 useEffect(()=>{const x=localStorage.getItem("oe-master-plan-2026-september");if(x)try{setBook(ensureBudget(JSON.parse(x)))}catch{}setAdmin(sessionStorage.getItem("oe-admin")==="1")},[]);
 const actions=book["06. Action Plan"].values.slice(2).filter(r=>r[2]);
 const penalties=useMemo(()=>calculatePenalties(book),[book]);
 const stats=useMemo(()=>({total:actions.length,done:actions.filter(r=>tx(r[6]).toLowerCase()==="done").length,late:actions.filter(r=>tx(r[6]).toLowerCase()==="late").length,going:actions.filter(r=>tx(r[6]).toLowerCase().includes("going")).length}),[book]);
 const members=book["01. OE Team"].values.slice(2).filter(r=>r[0]).length,completion=stats.total?Math.round(stats.done/stats.total*100):0;
 const update=(sheet:string,r:number,c:number,v:string)=>setBook(p=>{const n=structuredClone(p),raw=v.replace(/,/g,"").trim(),numericCell=(sheet==="KPI data tracking"&&r>=4&&c>=1&&c<=22)||(sheet==="03. Attendance"&&r>=3&&r<=12&&c===29)||(sheet==="OE meeting rules"&&r>=2&&(c===10||c===11))||(sheet==="Budget management"&&c>=1&&c<=3);n[sheet].values[r][c]=numericCell&&raw!==""&&Number.isFinite(Number(raw))?Number(raw):v;return n});
 const save=()=>{localStorage.setItem("oe-master-plan-2026-september",JSON.stringify(book));setSaved(true);setTimeout(()=>setSaved(false),1400)};
 const reset=()=>{setBook(freshBook());localStorage.removeItem("oe-master-plan-2026-september")};
 const download=()=>{const b=new Blob([JSON.stringify(book,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="OE_Master_Plan_2026_updates.json";a.click();URL.revokeObjectURL(a.href)};
 const login=async()=>{const bytes=new TextEncoder().encode(password),hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(b=>b.toString(16).padStart(2,"0")).join("");if(hash===ADMIN_HASH){setAdmin(true);sessionStorage.setItem("oe-admin","1");setLoginOpen(false);setPassword("");setLoginError(false)}else setLoginError(true)};
 const logout=()=>{setAdmin(false);sessionStorage.removeItem("oe-admin")};
 return <AdminContext.Provider value={admin}><main><header className="top"><div className="logo"><Sparkles/></div><div><p className="eyebrow">OPERATIONS EXCELLENCE</p><h1>OE Master Plan <b>2026</b></h1></div><div className="actions"><Button variant="outline" onClick={reset} disabled={!admin}><RefreshCw/> Reset</Button><Button variant="outline" onClick={download}><Download/> Export</Button><Button onClick={save} disabled={!admin}><Save/>{saved?"Saved":"Save changes"}</Button>{admin?<Button variant="outline" onClick={logout}><LogOut/>Log out</Button>:<Button variant="outline" onClick={()=>setLoginOpen(true)}><LockKeyhole/>Admin login</Button>}</div></header>
  <section className="overview"><div className="lead"><div><p className="eyebrow">PROGRAM SNAPSHOT</p><h2>One clear view of the 2026 execution plan.</h2><p>Track pillar activities, actions, attendance and factory KPIs. Click any cell to update it.</p></div><div className="ring" style={{background:`conic-gradient(#10a589 ${completion*3.6}deg,#dce8e9 0)`}}><div><strong>{completion}%</strong><small>completed</small></div></div></div><div className="metrics"><Metric icon={<Target/>} n={stats.total} label="Total actions" cls="navy"/><Metric icon={<CheckCircle2/>} n={stats.done} label="Completed" cls="green"/><Metric icon={<Clock3/>} n={stats.going} label="On going" cls="blue"/><Metric icon={<Activity/>} n={stats.late} label="Late actions" cls="red"/><Metric icon={<Users/>} n={members} label="OE members" cls="amber"/></div></section>
  <Tabs value={active} onValueChange={v=>{setActive(v);setQuery("");setMasterPillar("All");setMasterPic("All");setMulti({pillars:[],pics:[],statuses:[]})}} className="workspace"><div className="tabshell"><TabsList>{names.map(n=><TabsTrigger key={n} value={n}>{short[n]}</TabsTrigger>)}</TabsList></div>{names.map(n=><TabsContent key={n} value={n} className="panel">{n==="Budget management"?<BudgetManagement book={book} penalties={penalties} updateBudget={(r,c,v)=>update(n,r,c,v)} updateFund={(r,c,v)=>update("OE meeting rules",r,c,v)}/>:<SheetView name={n} sheet={book[n]} trackingRows={book["KPI data tracking"].values} penalties={penalties} query={query} setQuery={setQuery} masterPillar={masterPillar} setMasterPillar={setMasterPillar} masterPic={masterPic} setMasterPic={setMasterPic} multi={multi} setMulti={setMulti} update={(r,c,v)=>update(n,r,c,v)}/>}</TabsContent>)}</Tabs>
  <footer><span>OE Master Plan 2026</span><span>{admin?"Administrator editing mode":"Public view mode"}</span></footer>{loginOpen&&<div className="login-backdrop" role="dialog" aria-modal="true" aria-label="Administrator login"><form className="login-card" onSubmit={e=>{e.preventDefault();login()}}><button type="button" className="login-close" onClick={()=>{setLoginOpen(false);setLoginError(false)}}><X/></button><div className="login-icon"><LockKeyhole/></div><p className="eyebrow">ADMINISTRATION</p><h2>Administrator login</h2><p>Enter the management password to edit and save data.</p><Input autoFocus type="password" value={password} onChange={e=>{setPassword(e.target.value);setLoginError(false)}} placeholder="Password"/>{loginError&&<small className="login-error">Incorrect password. Please try again.</small>}<Button type="submit">Unlock editing</Button></form></div>}</main></AdminContext.Provider>
}
function Metric({icon,n,label,cls}:{icon:React.ReactNode;n:number;label:string;cls:string}){return <article className={"metric "+cls}><i>{icon}</i><div><strong>{n}</strong><span>{label}</span></div></article>}

function SheetView({name,sheet,trackingRows,penalties,query,setQuery,masterPillar,setMasterPillar,masterPic,setMasterPic,multi,setMulti,update}:{name:string;sheet:Sheet;trackingRows:Cell[][];penalties:Record<string,Penalty>;query:string;setQuery:(v:string)=>void;masterPillar:string;setMasterPillar:(v:string)=>void;masterPic:string;setMasterPic:(v:string)=>void;multi:Multi;setMulti:(v:Multi)=>void;update:(r:number,c:number,v:string)=>void}){
 const admin=useContext(AdminContext);
 const action=name==="06. Action Plan",master=name==="05. Master Planning",attendance=name==="03. Attendance",kpi=name==="KPI data tracking",measure=name==="7. KPI Measure",rows=sheet.values;
 const title=(rows.flat().find(v=>typeof v==="string"&&v.trim()) as string)||short[name];
 let inherited="";const indexed=rows.map((row,index)=>{if(master&&tx(row[0]))inherited=tx(row[0]);return{row,index,pillar:master?inherited:tx(row[2])}});
 const min=master?4:2,pillars=[...new Set(indexed.filter(x=>x.index>=min&&x.pillar).map(x=>x.pillar))],picCol=master?2:4,pics=[...new Set(rows.slice(min).map(r=>tx(r[picCol])).filter(Boolean))],statuses=[...new Set(rows.slice(2).map(r=>tx(r[6])).filter(Boolean))];
 const match=(x:{row:Cell[];index:number;pillar:string})=>!query||x.row.some(v=>tx(v).toLowerCase().includes(query.toLowerCase()));
 const filtered=indexed.filter(x=>match(x)&&(!master||((masterPillar==="All"||x.pillar===masterPillar)&&(masterPic==="All"||tx(x.row[2])===masterPic)))&&(!action||((!multi.pillars.length||multi.pillars.includes(x.pillar))&&(!multi.pics.length||multi.pics.includes(tx(x.row[4])))&&(!multi.statuses.length||multi.statuses.includes(tx(x.row[6]))))));
 return <><div className="panelhead"><div><p className="eyebrow">WORKSHEET</p><h2>{title}</h2><p>{attendance?"Attendance by meeting week":master?"Annual pillar roadmap by week":action?"Live follow-up list for OE commitments":kpi?"Factory targets and monthly actual performance":`${rows.filter(hasValue).length} spreadsheet rows imported`}</p></div><div className="tools"><div className="search"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search in sheet…"/></div>{master&&<><select value={masterPillar} onChange={e=>setMasterPillar(e.target.value)}><option value="All">All pillars</option>{pillars.map(v=><option key={v}>{v}</option>)}</select><select value={masterPic} onChange={e=>setMasterPic(e.target.value)}><option value="All">All PICs</option>{pics.map(v=><option key={v}>{v}</option>)}</select></>}{action&&<><MultiFilter label="Pillars" options={pillars} selected={multi.pillars} change={pillars=>setMulti({...multi,pillars})}/><MultiFilter label="PICs" options={pics} selected={multi.pics} change={pics=>setMulti({...multi,pics})}/><MultiFilter label="Status" options={statuses} selected={multi.statuses} change={statuses=>setMulti({...multi,statuses})}/></>}<span className={admin?"edit-mode":"view-mode"}>{admin?<Edit3/>:<LockKeyhole/>}{admin?"Editable":"View only"}</span></div></div>
  {master&&<div className="week-badge"><span>Current week</span><strong>W{isoWeek()}</strong><small>Monday – Sunday</small></div>}
  {measure?<KpiDashboard rows={trackingRows}/>:kpi?<KpiTrackingTable rows={rows} update={update}/>:attendance?<AttendanceTable rows={rows} penalties={penalties} update={update}/>:master?<MasterTable rows={filtered.filter(x=>x.index>=4||x.index===2||x.index===3)} update={update}/>:name==="OE meeting rules"?<MeetingRules rows={rows} update={update}/>:<PlainTable name={name} rows={(action?filtered.filter(x=>x.index>=1):filtered).filter(x=>hasValue(x.row))} action={action} update={update}/>}</>
}
function MultiFilter({label,options,selected,change}:{label:string;options:string[];selected:string[];change:(v:string[])=>void}){const toggle=(v:string)=>change(selected.includes(v)?selected.filter(x=>x!==v):[...selected,v]);return <details className="multifilter"><summary>{label}{selected.length>0&&<b>{selected.length}</b>}<ChevronDown/></summary><div><button onClick={()=>change([])} className="clear"><X/>Clear all</button>{options.map(v=><label key={v}><input type="checkbox" checked={selected.includes(v)} onChange={()=>toggle(v)}/><i>{selected.includes(v)&&<Check/>}</i><span>{v}</span></label>)}</div></details>}
function CellEditor({value,row,col,update,date=false,readOnly=false,currency=false,precision=1,percent=false}:{value:Cell;row:number;col:number;update:(r:number,c:number,v:string)=>void;date?:boolean;readOnly?:boolean;currency?:boolean;precision?:number;percent?:boolean}){const admin=useContext(AdminContext),locked=readOnly||!admin,numeric=currency||percent||typeof value==="number"&&!date,format=(v:Cell)=>v==null||v===""?"":percent?`${new Intl.NumberFormat("en-US",{minimumFractionDigits:precision,maximumFractionDigits:precision}).format(Number(v)*100)}%`:new Intl.NumberFormat("en-US",{minimumFractionDigits:precision,maximumFractionDigits:precision}).format(Number(v)),[draft,setDraft]=useState(numeric?format(value):date?excelDate(value):tx(value));useEffect(()=>setDraft(numeric?format(value):date?excelDate(value):tx(value)),[value,numeric,date,precision,percent]);const commit=()=>{if(!locked&&numeric){const parsed=draft.replace(/,/g,"").replace(/%/g,"");update(row,col,percent&&parsed!==""?String(Number(parsed)/100):parsed)}};return <textarea rows={1} value={draft} inputMode={numeric?"decimal":undefined} readOnly={locked} className={readOnly?"calculated":!admin?"viewer-cell":""} onChange={e=>{setDraft(e.target.value);if(!numeric&&!locked)update(row,col,e.target.value)}} onBlur={commit} aria-label={`Row ${row+1}, column ${col+1}`}/>}
function StatusEditor({value,row,col,update}:{value:Cell;row:number;col:number;update:(r:number,c:number,v:string)=>void}){const admin=useContext(AdminContext);return <select disabled={!admin} className={`status-select ${tone(value)}`} value={tx(value).replace("On going","Ongoing")} onChange={e=>update(row,col,e.target.value)} aria-label={`Status row ${row+1}`}><option value="">Select status</option>{["Done","Late","Ongoing","Cancel"].map(v=><option key={v}>{v}</option>)}</select>}
function PlainTable({name,rows,action,update}:{name:string;rows:{row:Cell[];index:number}[];action:boolean;update:(r:number,c:number,v:string)=>void}){const engagement=name==="Engagement plan",engagementTotal=engagement?rows.filter(x=>x.index>=2&&x.index<=8).reduce((sum,x)=>sum+(Number(x.row[7])||0)*(Number(x.row[8])||0),0):0;return <div className={"tablewrap "+(action?"actiontable":"")}><table><tbody>{rows.map(({row,index})=>{if(engagement&&index===0)return <tr key={index} className="engagement-title-row"><td colSpan={4} className="engagement-merged-title"><CellEditor value={row[0]} row={index} col={0} update={update}/></td><td className="engagement-spacer"/><td colSpan={5} className="engagement-merged-title"><CellEditor value={row[5]} row={index} col={5} update={update}/></td></tr>;return <tr key={index} className={index===1?"headrow":""}>{(action?row.slice(1):row).map((cell,k)=>{const c=action?k+1:k,formula=engagement&&c===9&&index>=2,display=formula?(index===9?engagementTotal:(Number(row[7])||0)*(Number(row[8])||0)):cell;return <td key={c} className={tone(display)+` col-${c} ${formula?"calculated-total":""}`}>{action&&index>=2&&c===6?<StatusEditor value={cell} row={index} col={c} update={update}/>:<CellEditor value={display} row={index} col={c} date={action&&c===5} readOnly={formula} update={update}/>}</td>})}</tr>})}</tbody></table></div>}

function AttendanceTable({rows,penalties,update}:{rows:Cell[][];penalties:Record<string,Penalty>;update:(r:number,c:number,v:string)=>void}){
 const cols=Array.from({length:31},(_,i)=>i),dataRows=rows.map((row,index)=>({row,index})).filter(x=>x.index>=1&&x.index<=13&&hasValue(x.row.slice(0,31)));
 const mergedHeader=(row:Cell[],ri:number)=>{const cells:React.ReactNode[]=[];for(let c=0;c<31;){const value=row[c];if(ri===1&&c>=4&&value){let span=1;while(c+span<31&&!row[c+span])span++;cells.push(<th key={c} colSpan={span}><CellEditor value={value} row={ri} col={c} update={update}/></th>);c+=span}else if(ri===1&&c<4){cells.push(<th key={c} rowSpan={2}><CellEditor value={value} row={ri} col={c} update={update}/></th>);c++}else if(ri===2&&c<4){c++}else{cells.push(<th key={c}><CellEditor value={value} row={ri} col={c} update={update}/></th>);c++}}return cells};
 const peopleRows=dataRows.filter(x=>x.index>=3&&x.index<=12); const totals={attendance:0,action:0,master:0,total:0,paid:0,remain:0};
 const body=peopleRows.map(({row,index})=>{const p=penalties[key(row[1])]||{opening:openingBalances[key(row[1])]||0,attendance:0,action:0,master:0,total:0},paid=Number(row[29])||0,remain=p.opening+p.total-paid;totals.attendance+=p.attendance;totals.action+=p.action;totals.master+=p.master;totals.total+=p.total;totals.paid+=paid;totals.remain+=remain;return <tr key={index}>{cols.map(c=>{const computed=c===25?p.attendance:c===26?p.action:c===27?p.master:c===28?p.total:c===30?remain:null;return <td key={c} className={tone(row[c])+` col-${c} ${c>=25?"money":""}`}><CellEditor value={computed??row[c]} row={index} col={c} currency={c>=25} readOnly={c>=25&&c!==29} update={update}/></td>})}</tr>});
 body.push(<tr key="totals" className="penalty-total">{cols.map(c=>{const computed=c===25?totals.attendance:c===26?totals.action:c===27?totals.master:c===28?totals.total:c===29?totals.paid:c===30?totals.remain:null;return <td key={c} className={c>=25?"money":""}>{c===24?<strong>TOTAL</strong>:computed!==null?<CellEditor value={computed} row={13} col={c} currency readOnly update={update}/>:null}</td>})}</tr>);
 return <><div className="formula-strip"><span><b>Attendance:</b> Late × 20,000 ₫ + Absent × 50,000 ₫</span><span><b>Action Plan:</b> Late count × 10,000 ₫</span><span><b>Master Planning:</b> Late milestone × 10,000 ₫</span></div><div className="tablewrap attendancetable"><table><thead><tr>{mergedHeader(rows[1],1)}</tr><tr>{mergedHeader(rows[2],2)}</tr></thead><tbody>{body}</tbody></table></div><div className="legend attendance-legend"><b>Attendance code</b><span className="done">1 · Ontime</span><span className="late">2 · Late</span><span className="going">3 · Absent</span><span className="muted">4 · NA</span></div></>
}
function MasterTable({rows,update}:{rows:{row:Cell[];index:number;pillar:string}[];update:(r:number,c:number,v:string)=>void}){
 const source=rows.length?rows[0].row:[],last=Math.max(3,...rows.flatMap(x=>x.row.map((v,i)=>v!==null&&v!==""?i:-1))),cols=Array.from({length:last+1},(_,i)=>i).filter(i=>i!==56),headers=rows.filter(x=>x.index===2||x.index===3),body=rows.filter(x=>x.index>=4&&hasValue(x.row));
 const pillarSpans=new Map<number,number>();for(let i=0;i<body.length;){const p=body[i].pillar;let n=1;while(i+n<body.length&&body[i+n].pillar===p)n++;pillarSpans.set(i,n);i+=n}
 return <div className="tablewrap mastertable"><table><thead>{headers.map(({row,index},hi)=><tr key={index}>{(()=>{const out:React.ReactNode[]=[];for(let p=0;p<cols.length;){const c=cols[p];if(hi===0&&c<4){out.push(<th key={c} rowSpan={2}><CellEditor value={row[c]} row={index} col={c} update={update}/></th>);p++;continue}if(hi===1&&c<4){p++;continue}if(hi===0&&row[c]){let span=1;while(p+span<cols.length&&!row[cols[p+span]])span++;out.push(<th key={c} colSpan={span}><CellEditor value={row[c]} row={index} col={c} update={update}/></th>);p+=span;continue}out.push(<th key={c}><CellEditor value={row[c]} row={index} col={c} update={update}/></th>);p++}return out})()}</tr>)}</thead><tbody>{body.map((x,i)=><tr key={x.index}>{cols.map(c=>{if(c===0&&i>0&&body[i-1].pillar===x.pillar)return null;return <td key={c} rowSpan={c===0?pillarSpans.get(i):undefined} className={tone(x.row[c])+` col-${c}`}><CellEditor value={c===0?x.pillar:x.row[c]} row={x.index} col={c} update={update}/></td>})}</tr>)}</tbody></table></div>
}
function MeetingRules({rows,update}:{rows:Cell[][];update:(r:number,c:number,v:string)=>void}){
 const rules=rows.map((row,index)=>({row,index})).filter(x=>x.index>=1&&hasValue(x.row.slice(0,4)));
 const compact=(items:{row:Cell[];index:number}[],start:number)=><div className="tablewrap compact-table"><table><tbody>{items.map(({row,index},i)=><tr key={index} className={`${i===0?"headrow":""} ${start===8&&index===12?"fund-input-row":""}`}>{row.slice(start,start+4).map((v,k)=><td key={k}><CellEditor value={v} row={index} col={start+k} date={start===8&&k===1} currency={start===8&&(k===2||k===3)} update={update}/></td>)}</tr>)}</tbody></table></div>;
 return <div className="rules-grid rules-single"><section><h3>Meeting rules & activities</h3>{compact(rules,0)}</section></div>
}
function KpiTrackingTable({rows,update}:{rows:Cell[][];update:(r:number,c:number,v:string)=>void}){
 const merged=(row:Cell[],ri:number,start=0)=>{const out:React.ReactNode[]=[];for(let c=start;c<24;){const value=row[c];if(c===0){out.push(<th key={c}><CellEditor value={value} row={ri} col={c} update={update}/></th>);c++;continue}let span=1;while(c+span<24&&!row[c+span])span++;out.push(<th key={c} colSpan={span}><CellEditor value={value} row={ri} col={c} update={update}/></th>);c+=span}return out};
 const actualTone=(row:Cell[],c:number)=>{const def=kpiDefs.find(k=>k.a===c);if(!def)return"";const actual=row[c],target=row[def.t];if(actual===null||actual===""||!Number.isFinite(Number(actual))||!Number.isFinite(Number(target)))return"kpi-na";return(def.higher?Number(actual)>=Number(target):Number(actual)<=Number(target))?"kpi-achieved":"kpi-missed"};
 const formatProps=(c:number)=>({precision:c>=5&&c<=8?2:1,percent:c===19||c===20});
 return <div className="tablewrap kpitracking"><table><thead><tr className="business-title"><th colSpan={24}><CellEditor value={rows[0][0]} row={0} col={0} update={update}/></th></tr><tr className="pic-row">{merged(rows[1],1)}</tr><tr className="kpi-row">{merged(rows[2],2)}</tr><tr className="target-row">{rows[3].map((v,c)=><th key={c}><CellEditor value={v} row={3} col={c} {...formatProps(c)} update={update}/></th>)}</tr></thead><tbody>{rows.slice(4).filter(hasValue).map((row,i)=><tr key={i+4}>{row.map((v,c)=><td key={c} className={`col-${c} ${actualTone(row,c)}`}><CellEditor value={v} row={i+4} col={c} {...formatProps(c)} update={update}/></td>)}</tr>)}</tbody></table></div>
}
const kpiDefs=[
 {name:"Converted Volume",pic:"Duc Mai",t:1,a:2,higher:true},{name:"RW Generation",pic:"Duy Pham",t:3,a:4,higher:false},{name:"Yield of VG2",pic:"Vu Tran",t:5,a:6,higher:false},{name:"Yield of Conilon",pic:"Vu Tran",t:7,a:8,higher:false},{name:"Turn-over",pic:"Yen Tran",t:9,a:10,higher:false},{name:"LTI",pic:"Hoang Nguyen",t:11,a:12,higher:false},{name:"Major Complaint",pic:"Dung Tran",t:13,a:14,higher:false},{name:"Other Complaint",pic:"Dung Tran",t:15,a:16,higher:false},{name:"Major Finding",pic:"Hoang Nguyen",t:17,a:18,higher:false},{name:"Cert. Renewal",pic:"Dung Tran",t:19,a:20,higher:true},{name:"Total NC",pic:"Dung Tran",t:21,a:22,higher:false}
];

function BudgetManagement({book,penalties,updateBudget,updateFund}:{book:Book;penalties:Record<string,Penalty>;updateBudget:(r:number,c:number,v:string)=>void;updateFund:(r:number,c:number,v:string)=>void}){
 const budget=book["Budget management"].values,attendance=book["03. Attendance"].values,rules=book["OE meeting rules"].values;
 const people=budget.slice(0,8).map((r,index)=>{const a=attendance.find(x=>key(x[1])===key(r[0])),p=penalties[key(r[0])]||{total:0},paid=Number(a?.[29])||0;return{row:r,index,punish:p.total||0,paid,remain:(openingBalances[key(r[0])]||0)+(p.total||0)-paid}});
 const budgetTotal=people.reduce<number>((s,x)=>s+x.row.slice(1,4).reduce<number>((n,v)=>n+(Number(v)||0),0),0),punishTotal=people.reduce<number>((s,x)=>s+x.punish,0),paidTotal=people.reduce<number>((s,x)=>s+x.paid,0),remainTotal=people.reduce<number>((s,x)=>s+x.remain,0);
 const fundRows=rules.map((row,index)=>({row,index})).filter(x=>x.index>=4&&x.index<=12&&hasValue(x.row.slice(8,12))),extraFundRows=budget.slice(8,13).map((row,i)=>({row,index:i+8})),fund=940000+budgetTotal+paidTotal,payment=Math.abs(rules.slice(2,13).reduce((s,r)=>s+(Number(r[11])||0),0)+extraFundRows.reduce((s,x)=>s+(Number(x.row[2])||0),0)),fundRemain=fund-payment;
 return <><div className="panelhead"><div><p className="eyebrow">FINANCE WORKSHEET</p><h2>Budget Management</h2><p>Quarterly member budget, attendance penalties and OE fund tracking</p></div></div><div className="budget-grid"><section className="budget-card"><h3>Budget Management</h3><div className="tablewrap"><table><thead><tr><th rowSpan={2}>Name</th><th colSpan={3}>Budget</th><th rowSpan={2}>Punish</th><th rowSpan={2}>Fine Paid</th><th rowSpan={2}>Punish Remain</th></tr><tr><th>Quarter 2</th><th>Quarter 3</th><th>Quarter 4</th></tr></thead><tbody>{people.map(x=><tr key={x.index}><td><CellEditor value={x.row[0]} row={x.index} col={0} update={updateBudget}/></td>{[1,2,3].map(c=><td key={c}><CellEditor value={x.row[c]} row={x.index} col={c} currency update={updateBudget}/></td>)}<td className="linked-cell"><CellEditor value={x.punish} row={x.index} col={4} currency readOnly update={updateBudget}/></td><td className="linked-cell"><CellEditor value={x.paid} row={x.index} col={5} currency readOnly update={updateBudget}/></td><td className="linked-cell"><CellEditor value={x.remain} row={x.index} col={6} currency readOnly update={updateBudget}/></td></tr>)}<tr className="budget-total"><td>Total</td><td colSpan={3}>{formatNumber(budgetTotal)}</td><td>{formatNumber(punishTotal)}</td><td>{formatNumber(paidTotal)}</td><td>{formatNumber(remainTotal)}</td></tr></tbody></table></div><div className="fund-summary"><div><span>Fund</span><strong>{formatNumber(fund)}</strong></div><div><span>Payment</span><strong>{formatNumber(payment)}</strong></div><div><span>Remain</span><strong>{formatNumber(fundRemain)}</strong></div></div></section><section className="budget-card fund-tracking"><h3>OE Fund Tracking</h3><div className="tablewrap"><table><thead><tr><th>Activities</th><th>Date</th><th>Payment</th></tr></thead><tbody>{fundRows.map(({row,index})=><tr key={`source-${index}`}><td><CellEditor value={row[8]} row={index} col={8} update={updateFund}/></td><td><CellEditor value={row[9]} row={index} col={9} date update={updateFund}/></td><td><CellEditor value={row[11]} row={index} col={11} currency update={updateFund}/></td></tr>)}{extraFundRows.map(({row,index})=><tr key={`extra-${index}`} className="new-fund-row"><td><CellEditor value={row[0]} row={index} col={0} update={updateBudget}/></td><td><CellEditor value={row[1]} row={index} col={1} date update={updateBudget}/></td><td><CellEditor value={row[2]} row={index} col={2} currency update={updateBudget}/></td></tr>)}<tr className="budget-total"><td colSpan={2}>Total payment</td><td>{formatNumber(-payment)}</td></tr></tbody></table></div></section></div></>
}
function KpiDashboard({rows}:{rows:Cell[][]}){
 const months=rows.slice(4,16),completion=months.map(r=>({month:tx(r[0]),complete:Math.round(kpiDefs.filter(k=>r[k.a]!==null&&r[k.a]!=="").length/kpiDefs.length*100)}));
 return <div className="dashboard-grid">{kpiDefs.map(k=>{const data=months.map(r=>{const target=Number.isFinite(Number(r[k.t]))?Number(r[k.t]):null,actual=r[k.a]!==null&&r[k.a]!==""&&Number.isFinite(Number(r[k.a]))?Number(r[k.a]):null;return{month:tx(r[0]),target,actual,achieved:actual===null||target===null?null:k.higher?actual>=target:actual<=target}}),latest=[...data].reverse().find(d=>d.actual!==null);return <article className="kpi-card" key={k.name}><header><div><span>{k.pic}</span><h3>{k.name}</h3></div><div className="latest"><small>Latest actual</small><strong>{latest?formatNumber(latest.actual):"—"}</strong></div></header><div className="mini-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{top:24,right:2,left:-12,bottom:0}} barGap={1}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2eaeb"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:10}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:10}} tickFormatter={v=>formatNumber(v)}/><Tooltip formatter={v=>v==null?"—":formatNumber(Number(v))}/><Bar dataKey="target" name="Target" fill="#cbd7d9" radius={[4,4,0,0]} maxBarSize={10}/><Bar dataKey="actual" name="Actual" radius={[5,5,0,0]} maxBarSize={16}>{data.map((d,i)=><ChartCell key={i} fill={d.achieved===null?"#9aaeb2":d.achieved?"#14966f":"#d94f5c"}/>) }<LabelList dataKey="actual" position="top" formatter={(v:unknown)=>v==null?"":formatNumber(Number(v))} className="actual-label"/></Bar></BarChart></ResponsiveContainer></div><footer><span><i style={{background:"#14966f"}}/>Achieved</span><span><i style={{background:"#d94f5c"}}/>Below target</span><span><i style={{background:"#cbd7d9"}}/>Target</span></footer></article>})}<article className="kpi-card completion-card"><header><div><span>DATA QUALITY</span><h3>KPI Data Completion</h3></div><div className="latest"><small>Current</small><strong>{formatNumber(completion.find(x=>x.month==="Aug")?.complete??completion[0]?.complete)}%</strong></div></header><div className="mini-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={completion} margin={{top:24,right:6,left:-18,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2eaeb"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:10}}/><YAxis domain={[0,100]} axisLine={false} tickLine={false} tick={{fontSize:10}} tickFormatter={v=>formatNumber(v)}/><Tooltip formatter={v=>`${formatNumber(Number(v))}%`}/><Bar dataKey="complete" name="Completed fields" fill="#0d6267" radius={[5,5,0,0]}><LabelList dataKey="complete" position="top" formatter={(v:unknown)=>`${formatNumber(Number(v))}%`} className="actual-label"/></Bar></BarChart></ResponsiveContainer></div><footer><span>Actual fields entered by month</span></footer></article></div>
}
